### ISSUE TITLE
flutter run报错：The following dependencies do not satisfy the required version

### ISSUE THREAD

**Issue by J-Yaleen** [50431040/flutter_gromore#10]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_gromore' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by 50431040** [comment]
修改kotlin插件版本

**Comment by J-Yaleen** [comment]
改了 但是跑不起来
```
// pubspec.yaml
  flutter_gromore:
    git:
      url: https://hub.fgit.ml/J-Yaleen/flutter_gromore.git
      ref: main
```
我只加了这个文件 其他还有修改什么吗
